[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on   = "M"
run  = "plugin mediainfo -- toggle-preview"
desc = "Toggle mediainfo preview image"

[[mgr.prepend_keymap]]
on   = "<C-m>"
run  = "plugin mediainfo -- toggle-metadata"
desc = "Toggle mediainfo metadata"
